package org.infobip.mobile.messaging;

import android.content.BroadcastReceiver;

import org.infobip.mobile.messaging.geo.Geo;

/**
 * Enumerates all events generated by the Mobile Messaging library.
 * It is intended to be used in <i>BroadcastReceivers</i> registered locally or at the application level.
 * <p>
 * You can register receivers in AndroidManifest.xml by adding:
 * <pre>
 * {@code <receiver android:name=".MyMessageReceiver" android:exported="false">
 *       <intent-filter>
 *           <action android:name="org.infobip.mobile.messaging.MESSAGE_RECEIVED"/>
 *        </intent-filter>
 *   </receiver>}
 * </pre>
 * <p>
 * You can also register receivers in you Activity by adding:
 * <pre>
 * {@code
 * public class MyActivity extends AppCompatActivity {
 *        private boolean isReceiverRegistered;
 *        private BroadcastReceiver messageReceiver = new BroadcastReceiver() {
 *            public void onReceive(Context context, Intent intent) {
 *                Message message = new Message(intent.getExtras());
 *                ... process your message here
 *            }
 *        };
 *
 *        protected void onCreate(Bundle savedInstanceState) {
 *            super.onCreate(savedInstanceState);
 *
 *            registerReceiver();
 *        }
 *
 *        protected void onResume() {
 *            super.onResume();
 *            registerReceiver();
 *        }
 *
 *        protected void onPause() {
 *            LocalBroadcastManager.getInstance(this).unregisterReceiver(messageReceiver);
 *            isReceiverRegistered = false;
 *            super.onPause();
 *        }
 *
 *        private void registerReceiver() {
 *            if (isReceiverRegistered) {
 *                return;
 *            }
 *            LocalBroadcastManager.getInstance(this).registerReceiver(messageReceiver,
 *            new IntentFilter(Event.MESSAGE_RECEIVED.getKey()));
 *            isReceiverRegistered = true;
 *        }
 *    }}
 * </pre>
 *
 * @author mstipanov
 * @see BroadcastReceiver
 * @see Event#MESSAGE_RECEIVED
 * @see Event#REGISTRATION_ACQUIRED
 * @see Event#REGISTRATION_CREATED
 * @see Event#DELIVERY_REPORTS_SENT
 * @see Event#API_COMMUNICATION_ERROR
 * @since 01.03.2016.
 */
public enum Event {
    /**
     * It is triggered when GCM registration token is received.
     * <p>
     * Contains the GCM registration token.
     * <pre>
     * {@code
     * String gcmRegistrationToken = intent.getStringExtra({@link BroadcastParameter#EXTRA_GCM_TOKEN});
     * }
     * </pre>
     */
    REGISTRATION_ACQUIRED("org.infobip.mobile.messaging.REGISTRATION_ACQUIRED"),

    /**
     * It is triggered when GCM registration token successfully stored on the registration server.
     * <p>
     * Contains the GCM registration token and Infobip device application instance ID
     * (which identifies every application instance).
     * <pre>
     * {@code
     * String registrationId = intent.getStringExtra({@link BroadcastParameter#EXTRA_GCM_TOKEN});
     * String deviceApplicationInstanceId = intent.getStringExtra({@link BroadcastParameter#EXTRA_INFOBIP_ID});
     * }
     * </pre>
     */
    REGISTRATION_CREATED("org.infobip.mobile.messaging.REGISTRATION_CREATED"),

    /**
     * It is triggered when message is received.
     * <p>
     * Contains the received message information.
     * <pre>
     * {@code
     * Message message = new Message(intent.getExtras());
     * }
     * </pre>
     *
     * @see Message
     */
    MESSAGE_RECEIVED("org.infobip.mobile.messaging.MESSAGE_RECEIVED"),

    /**
     * It is triggered when messages are sent.
     * <p>
     * Contains messages that were sent and status information for each message.
     * <pre>
     * {@code
     * Message messages[] = Message.createFrom(intent.getParcelableArrayListExtra(BroadcastParameter.EXTRA_MESSAGES));
     * }
     * </pre>
     *
     * @see Message
     */
    MESSAGES_SENT("org.infobip.mobile.messaging.MESSAGES_SENT"),

    /**
     * It is triggered on every error returned by API.
     * <p>
     * Contains the exception information.
     * <pre>
     * {@code
     * Throwable exception = (Throwable) intent.getSerializableExtra({@link BroadcastParameter#EXTRA_EXCEPTION });
     * }
     * </pre>
     */
    API_COMMUNICATION_ERROR("org.infobip.mobile.messaging.API_COMMUNICATION_ERROR"),

    /**
     * It is triggered when message delivery is reported.
     * <p>
     * Contains the list of all reported message IDs.
     * <pre>
     * {@code
     * String[] messageIDs = intent.getStringArrayExtra({@link BroadcastParameter#EXTRA_MESSAGE_IDS});
     * }
     * </pre>
     */
    DELIVERY_REPORTS_SENT("org.infobip.mobile.messaging.DELIVERY_REPORTS_SENT"),

    /**
     * It is triggered when message seen is reported.
     * <p>
     * Contains the list of all reported message IDs.
     * <pre>
     * {@code
     * String[] messageIDs = intent.getStringArrayExtra({@link BroadcastParameter#EXTRA_MESSAGE_IDS});
     * }
     * </pre>
     */
    SEEN_REPORTS_SENT("org.infobip.mobile.messaging.SEEN_REPORTS_SENT"),

    /**
     * It is triggered when monitored geofence area is entered.
     * <p>
     * Contains the {@link Geo} object which contains the list of all triggered geofence areas and {@link Message}.
     * <pre>
     * {@code
     * Geo geofenceAreas = intent.getParcelableExtra(BroadcastParameter.EXTRA_GEOFENCE_AREAS);
     * Message message = Message.createFrom(intent.getBundleExtra(BroadcastParameter.EXTRA_MESSAGE));
     * }
     * </pre>
     */
    GEOFENCE_AREA_ENTERED("org.infobip.mobile.messaging.GEOFENCE_AREA_ENTERED"),

    /**
     * It is triggered when user data is successfully reported to the server.
     * <pre>
     * {@code
     * UserData userData = new UserData(intent.getStringExtra(BroadcastParameter.EXTRA_USER_DATA));
     * }
     * </pre>
     */
    USER_DATA_REPORTED("org.infobip.mobile.messaging.USER_DATA_REPORTED"),

    /**
     * It is triggered when system data is successfully reported to the server.
     * <pre>
     * {@code
     * String systemData = intent.getStringExtra(BroadcastParameter.EXTRA_SYSTEM_DATA);
     * }
     * </pre>
     */
    SYSTEM_DATA_REPORTED("org.infobip.mobile.messaging.SYSTEM_DATA_REPORTED"),

    /**
     * It is triggered when Google Play Services are not available.
     * <pre>
     * {@code
     * int playServicesErrorCode = intent.getIntExtra(BroadcastParameter.EXTRA_PLAY_SERVICES_ERROR_CODE);
     * }
     * </pre>
     */
    GOOGLE_PLAY_SERVICES_ERROR("org.infobip.mobile.messaging.GOOGLE_PLAY_SERVICES_ERROR");

    private final String key;

    Event(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
