package org.infobip.mobile.messaging.tools;

import android.content.Context;

import org.infobip.mobile.messaging.Message;
import org.infobip.mobile.messaging.MobileMessagingCore;
import org.infobip.mobile.messaging.geo.Area;
import org.infobip.mobile.messaging.geo.Geo;
import org.infobip.mobile.messaging.geo.GeoEventSettings;
import org.infobip.mobile.messaging.geo.GeoEventType;
import org.infobip.mobile.messaging.geo.GeoLatLng;
import org.infobip.mobile.messaging.geo.GeoReport;
import org.infobip.mobile.messaging.util.StringUtils;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * @author sslavin
 * @since 13/02/2017.
 */

public class Helper {

    /**
     * Generates messages with provided ids
     * @param saveToStorage set to true to save messages to message store
     * @param messageId message id for a message
     * @param campaignId id of a campaign for a message
     * @param areas list of areas to save to message
     * @return new message
     */
    public static Message createMessage(Context context, String messageId, String campaignId, boolean saveToStorage, Area... areas) {
        Message message = new Message();
        message.setMessageId(messageId);
        if (StringUtils.isNotBlank(campaignId)) {
            message.setGeo(new Geo(0.0, 0.0, null, null, null, campaignId, Arrays.asList(areas), new ArrayList<GeoEventSettings>()));
        }
        if (saveToStorage) {
            MobileMessagingCore.getInstance(context).getMessageStore().save(context, message);
        }
        return message;
    }

    /**
     * Generates geo report for the provided data
     * @param signalingMessageId signaling message id for report
     * @param campaignId campaign id for a report
     * @param sdkMessageId id of message generated by sdk
     * @param saveAsUnreported set to true to save report as unreported
     * @param area area to insert into report
     * @return geo report
     */
    public static GeoReport createReport(Context context, String signalingMessageId, String campaignId, String sdkMessageId, boolean saveAsUnreported, Area area) {
        GeoReport report = new GeoReport(
                campaignId,
                sdkMessageId,
                signalingMessageId,
                GeoEventType.entry,
                area == null ? new Area("areaId", "areaTitle", 1.0, 2.0, 3) : area,
                1L,
                new GeoLatLng(1.0, 2.0));

        if (saveAsUnreported) {
            MobileMessagingCore.getInstance(context).addUnreportedGeoEvents(report);
        }

        return report;
    }

    /**
     * Generates geo report for the provided data
     * @param signalingMessageId signaling message id for report
     * @param campaignId campaign id for a report
     * @param sdkMessageId id of message generated by sdk
     * @param saveAsUnreported set to true to save report as unreported
     * @return geo report
     */
    public static GeoReport createReport(Context context, String signalingMessageId, String campaignId, String sdkMessageId, boolean saveAsUnreported) {
        return createReport(context, signalingMessageId, campaignId, sdkMessageId, saveAsUnreported, null);
    }

    /**
     * Generates area
     * @param areaId id of an area
     * @return new area
     */
    public static Area createArea(String areaId) {
        return new Area(areaId, "", 1.0, 1.0, 1);
    }
}
