buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$mm_gradlePluginVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$mm_kotlinVersion"
    }
}

plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace = "org.infobip.mobile.messaging.chat"
    buildToolsVersion = mm_buildToolsVersion
    compileSdk = mm_compileSdkVersion

    publishing {
        singleVariant("release") {
            withJavadocJar()
            withSourcesJar()
        }
    }

    defaultConfig {
        minSdkVersion mm_minSdkVersion

        // since AGP 4.1 "VERSION_NAME" is not included anymore to BuildConfig
        // https://issuetracker.google.com/issues/154275579
        buildConfigField "String", "VERSION_NAME", "\"$versionName\""
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        consumerProguardFiles 'proguard-rules.pro'
        vectorDrawables.useSupportLibrary = true
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        debug {
            //needed for androidTests
            multiDexEnabled = true
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
        targetSdk 37
    }

    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    testOptions {
        targetSdk 37
    }


}

dependencies {
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }

    implementation project(":infobip-mobile-messaging-android-sdk")
    implementation project(":infobip-mobile-messaging-api-java")
    api project(":infobip-mobile-messaging-android-resources")

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$mm_kotlinVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$mm_coroutinesVersion"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$mm_lifecycleVersion"

    implementation "androidx.core:core-ktx:$mm_coreKtxVersion"
    implementation "androidx.constraintlayout:constraintlayout:$mm_constraintLayoutVersion"
    implementation "androidx.appcompat:appcompat:$mm_appCompatVersion"
    implementation "androidx.activity:activity-ktx:$mm_activityVersion"
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
    implementation "com.google.android.material:material:$mm_materialVersion"

    testImplementation project(":infobip-mobile-messaging-android-test")
    testImplementation "junit:junit:$mm_junitVersion"
    testImplementation "io.mockk:mockk:1.13.9"
    testImplementation "org.assertj:assertj-core:3.26.0"

    androidTestImplementation "androidx.test:runner:$mm_androidTestRunnerVersion"
    androidTestImplementation "androidx.test.ext:junit:$mm_androidJunitVersion"
    androidTestImplementation "junit:junit:$mm_junitVersion"
    androidTestImplementation "io.mockk:mockk-android:1.13.11"
    androidTestImplementation "androidx.multidex:multidex:$mm_multidexVersion"
}


ext {
    PUBLISH_ARTIFACT_ID = 'infobip-mobile-messaging-android-chat-sdk'
}
apply from: "${rootProject.projectDir}/publish-mavencentral.gradle"
apply from: "${rootProject.projectDir}/jacoco.gradle"